### ISSUE TITLE
Feature Request: VS Code

### ISSUE THREAD

**Issue by Kvanrooyen** [MidnightSprucePine/MidnightSprucePine-VSTheme#1]
Will you be making a version for VS Code? I really like the colour scheme but use VS Code more than Visual Studio

**Comment by hawkeye4077mash** [comment]
I sure will.  I'm currently working on it now.  I will let you know the moment it's released.  Should be finished in the next 24/48 hours.

**Comment by jasonhartsoe** [comment]
> Will you be making a version for VS Code? I really like the colour scheme but use VS Code more than Visual Studio

Just release the Code version.  You can download it directly here: https://github.com/MidnightSprucePine/MidnightSprucePine-VSCodeTheme .
